/**********************************

**********************************/
#ifndef __FOC_DEFINE_PARAMETER_H_
#define __FOC_DEFINE_PARAMETER_H_

#define MOTOR_STARTUP_CURRENT   2.5f
#define COMPRESSOR_STARTUP_ID_CURRENT   3.0f
#define COMPRESSOR_STARTUP_RUN_ID_CURRENT 3.0f
#define COMPRESSOR_STARTUP_HOLD_CURRENT 2.5f
#define COMPRESSOR_STARTUP_IQ_RAMP_A_S  0.375f
#define COMPRESSOR_STARTUP_IQ_STEP_A    (COMPRESSOR_STARTUP_IQ_RAMP_A_S * FOC_PERIOD)
#define SPEED_LOOP_CLOSE_RAD_S  120.0f

// Compressor open-loop product profile for the 8-pole Panasonic 6MD030Z.
#define COMPRESSOR_PRODUCT_OPEN_LOOP_ENABLE 1
#define COMPRESSOR_SAFE_START_ENABLE        1
#define COMPRESSOR_POLE_PAIRS               4u
#define COMPRESSOR_CONTROL_PERIOD_MS        10u
#define COMPRESSOR_RPM_TO_EHZ(rpm)          ((rpm) * (float)COMPRESSOR_POLE_PAIRS / 60.0f)
#define COMPRESSOR_EHZ_TO_RPM(hz)           ((hz) * 60.0f / (float)COMPRESSOR_POLE_PAIRS)
#define COMPRESSOR_EC11_MIN_RPM             450.0f
#define COMPRESSOR_EC11_MAX_RPM             1200.0f
#define COMPRESSOR_EC11_DEFAULT_RPM         1200.0f
#define COMPRESSOR_EC11_STEP_RPM            60.0f
#define COMPRESSOR_EC11_DIRECTION           -1
#define COMPRESSOR_AUTO_TEST_ENABLE         0
#define COMPRESSOR_AUTO_TEST_START_DELAY_MS 2000u
#define COMPRESSOR_AUTO_TEST_RUN_MS         100000u
#define COMPRESSOR_AUTO_TEST_HOLD_BOOST_ENABLE 0
#define COMPRESSOR_OPEN_LOOP_STARTUP_BOOST_RPM COMPRESSOR_EC11_DEFAULT_RPM
#define COMPRESSOR_OPEN_LOOP_STARTUP_BOOST_HZ  COMPRESSOR_RPM_TO_EHZ(COMPRESSOR_OPEN_LOOP_STARTUP_BOOST_RPM)
#define COMPRESSOR_MIN_SPEED_HZ             COMPRESSOR_RPM_TO_EHZ(COMPRESSOR_EC11_MIN_RPM)
#define COMPRESSOR_DEFAULT_SPEED_HZ         COMPRESSOR_RPM_TO_EHZ(COMPRESSOR_EC11_DEFAULT_RPM)
#define COMPRESSOR_MAX_SPEED_HZ             COMPRESSOR_RPM_TO_EHZ(COMPRESSOR_EC11_MAX_RPM)
#define COMPRESSOR_SPEED_STEP_HZ            COMPRESSOR_RPM_TO_EHZ(COMPRESSOR_EC11_STEP_RPM)
#define COMPRESSOR_RAMP_RATE_HZ_S           20.0f
#define COMPRESSOR_RAMP_STEP_HZ             (COMPRESSOR_RAMP_RATE_HZ_S * 0.01f)
#define COMPRESSOR_FORCE_START_ENABLE       1
#define COMPRESSOR_OPEN_LOOP_HOLD_ENABLE    1
#define COMPRESSOR_OPEN_LOOP_ALIGN_MS       1000u
#define COMPRESSOR_OPEN_LOOP_START_HZ       1.0f
#define COMPRESSOR_OPEN_LOOP_MAX_HZ         COMPRESSOR_MAX_SPEED_HZ
#define COMPRESSOR_OPEN_LOOP_CAL_HZ_LOW     30.0f
#define COMPRESSOR_OPEN_LOOP_CAL_HZ_MID     45.0f
#define COMPRESSOR_OPEN_LOOP_CAL_HZ_HIGH    60.0f
#define COMPRESSOR_OPEN_LOOP_DEFAULT_HZ     COMPRESSOR_DEFAULT_SPEED_HZ
#define COMPRESSOR_OPEN_LOOP_ACCEL_HZ_S     2.0f
#define COMPRESSOR_OPEN_LOOP_DECEL_HZ_S     8.0f
#define COMPRESSOR_OPEN_LOOP_RAMP_HZ_S      COMPRESSOR_OPEN_LOOP_ACCEL_HZ_S
#define COMPRESSOR_OPEN_LOOP_DIRECTION      1.0f
#define COMPRESSOR_OPEN_LOOP_ID_DECAY_START_HZ 130.0f
#define COMPRESSOR_OPEN_LOOP_ID_DECAY_END_HZ   180.0f
#define COMPRESSOR_OPEN_LOOP_HIGH_SPEED_ID_A   1.5f
#define COMPRESSOR_OPEN_LOOP_STALL_DETECT_ENABLE 1
#define COMPRESSOR_OPEN_LOOP_STALL_MIN_HZ      30.0f
#define COMPRESSOR_OPEN_LOOP_STALL_RATIO_MIN   0.35f
#define COMPRESSOR_OPEN_LOOP_STALL_CONFIRM_MS  800u
#define COMPRESSOR_VBUS_MIN_V              9.0f
#define COMPRESSOR_VBUS_MAX_V              15.5f
#define COMPRESSOR_PHASE_CURRENT_LIMIT_A   6.0f
#define COMPRESSOR_PHASE_CURRENT_FAST_LIMIT_A 10.0f
#define COMPRESSOR_CURRENT_FEEDFORWARD_ENABLE 0
#define COMPRESSOR_CURRENT_PI_CORRECTION_LIMIT_V 8.0f
#define COMPRESSOR_CURRENT_VOLTAGE_LIMIT_V 10.0f
#define COMPRESSOR_OPEN_LOOP_VF_ENABLE     0
#define COMPRESSOR_OPEN_LOOP_VF_START_HZ   110.0f
#define COMPRESSOR_OPEN_LOOP_VF_VD_V       0.5f
#define COMPRESSOR_OPEN_LOOP_VF_VQ_OFFSET_V -0.86f
#define COMPRESSOR_OPEN_LOOP_VF_VQ_PER_HZ  0.056f
#define COMPRESSOR_OPEN_LOOP_VF_VQ_LIMIT_V 9.0f
#define COMPRESSOR_OPEN_LOOP_THETA_LAG_START_HZ 100.0f
#define COMPRESSOR_OPEN_LOOP_THETA_LAG_END_HZ   130.0f
#define COMPRESSOR_OPEN_LOOP_THETA_LAG_MAX_RAD  0.0f
#define COMPRESSOR_IQ_LIMIT_A              4.0f
#define COMPRESSOR_REGEN_IQ_LIMIT_A        2.0f
#define COMPRESSOR_STARTUP_CHECK_MS        150000u
#define COMPRESSOR_STALL_CONFIRM_MS        3000u
#define COMPRESSOR_STALL_SPEED_HZ          8.0f
#define COMPRESSOR_RESTART_DELAY_MS        10000u
#define COMPRESSOR_VBUS_FAULT_COUNT        20u
#define COMPRESSOR_CURRENT_FAULT_COUNT     50u
#define COMPRESSOR_FAST_CURRENT_FAULT_COUNT 8u

// FOC mode selection. Enable exactly one mode.
//#define HALL_FOC_SELECT
#define SENSORLESS_FOC_SELECT

// Panasonic 6MD030Z EKF seed values. Rs is per phase; datasheet line-line R is 0.376 ohm.
#define RS_PARAMETER     0.188f
#define LS_PARAMETER     0.00036f
#define FLUX_PARAMETER   0.00580f

// EKF input signs. These only affect the observer, not FOC actuation.
#define EKF_V_ALPHA_SIGN  1.0f
#define EKF_V_BETA_SIGN   1.0f
#define EKF_I_ALPHA_SIGN  1.0f
#define EKF_I_BETA_SIGN   1.0f

// EKF handoff. Open-loop angle is used until the observer passes the takeover gate.
#define EKF_HANDOFF_DIAG_ENABLE          1
#define EKF_HANDOFF_BLEND_ENABLE         0
#define EKF_HANDOFF_MIN_HZ               25.0f
#define EKF_HANDOFF_TARGET_TOL_HZ        0.5f
#define EKF_HANDOFF_SPEED_RATIO_MIN      0.90f
#define EKF_HANDOFF_SPEED_RATIO_MAX      1.10f
#define EKF_HANDOFF_DECAY_SPEED_RATIO_MIN 0.94f
#define EKF_HANDOFF_DECAY_SPEED_RATIO_MAX 1.06f
#define EKF_HANDOFF_DECAY_ANGLE_ERR_MAX_RAD 0.90f
#define EKF_HANDOFF_RUN_SPEED_RATIO_MIN  0.75f
#define EKF_HANDOFF_RUN_SPEED_RATIO_MAX  1.25f
#define EKF_HANDOFF_ANGLE_ERR_MAX_RAD    0.70f
#define EKF_HANDOFF_RUNTIME_ANGLE_TRIP   0
#define EKF_HANDOFF_READY_TICKS          10000u
#define EKF_HANDOFF_DECAY_READY_TICKS    10000u
#define EKF_HANDOFF_DECAY_TICKS          80000u
#define EKF_HANDOFF_BLEND_TICKS          80000u
#define EKF_HANDOFF_RUNTIME_BAD_TICKS    1000u
#define EKF_HANDOFF_FINAL_ID_CURRENT     0.0f
#define EKF_HANDOFF_FINAL_IQ_CURRENT     2.5f
#define EKF_HANDOFF_STICKY_FALLBACK      1

#endif
